
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true


# TODO: how to give space C a description?
# [keys.normal.space]
# C = "Config Actions..."

[keys.normal.space.C]
C = ":config-open"
R = ":config-reload"
W = ":config-open-workspace"
L = ":o ~/.config/helix/languges.toml"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-h" = ":buffer-previous"
"A-l" = ":buffer-next"
# C-l = ""
C-r = "redo"


# NOTE: all from https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# vim muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

# nice helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection" 
C-l = "select_next_sibling"

[keys.insert]
"A-h" = ":buffer-previous"
"A-l" = ":buffer-next"
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
# [keys.insert.j]
# k = "normal_mode" # Maps `jk` to exit insert mode

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

# NOTE: all from https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
# NOTE: Commenting because learning helix kb
# D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
# C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
