import = ['C:\Users\dgonz\AppData\Roaming\alacritty\catppuccin\catppuccin-macchiato.toml']

working_directory="C:\\Users\\dgonz"
shell="cmd.exe /s /k %cmder_root%/vendor/init.bat"

[env]
TERM = "xterm-256color"

# [font.normal]
# family = "MesloLGL Nerd Font"
# size = 9.0
[font]
size = 11.0
normal = { family = "IosevkaTerm Nerd Font" }
bold = { family = "IosevkaTerm Nerd Font" }
italic = { family = "IosevkaTerm Nerd Font" }
bold_italic = { family = "IosevkaTerm Nerd Font" }
